services:
  user-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/user-service:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    # environment:
    #   SERVER_PORT: ${SERVER_PORT}
    #   SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    #   SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    #   SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    #   KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    #   JWT_SECRET: ${JWT_SECRET}
    #   POINT_SERVICE_URL: ${POINT_SERVICE_URL}