services:
  user-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/user-service:latest
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT
      JWT_SECRET: ${JWT_SECRET}
      POINT_SERVICE_URL: http://${POINT_SERVICE_HOST}:8080
