name: user-service integration

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Configure AWS credentials
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          # ,linux/arm64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/board-system/user-service:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/board-system/user-service:latest
        
      - name: ec2 SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          SERVER_PORT: 8080
          SPRING_DATASOURCE_URL: jdbc:mysql://${{ secrets.DB_HOST }}:3306/user_db
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_SERVER_HOST }}:${{ secrets.KAFKA_SERVER_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          POINT_SERVICE_URL: http://${{ secrets.POINT_SERVICE_HOST }}
        with:
          host: ${{ secrets.USER_SERVICE_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: >
            SERVER_PORT,
            SPRING_DATASOURCE_URL,
            SPRING_DATASOURCE_USERNAME,
            SPRING_DATASOURCE_PASSWORD,
            KAFKA_BOOTSTRAP_SERVERS,
            JWT_SECRET,
            POINT_SERVICE_URL
          script_stop: true
          script: |
            cd /home/ubuntu/msa-user-service

            git fetch origin
            git reset --hard origin/master
            git clean -fd
            
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com
            docker compose pull
            docker compose up -d
  
      # - name: send trigger
      #   run: |
      #     curl -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer ${{ secrets.PAT }}" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       https://api.github.com/repos/yunjeongwon/msa-infra/dispatches \
      #       -d '{"event_type":"deploy","client_payload":{"service":"user-service"}}'
  