name: user-service integration

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      # - name: Configure AWS credentials
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v2
      
      # - name: Build, tag, and push docker image to Amazon ECR
      #   env:
      #     REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     REPOSITORY: user-service
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
      #     docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/msa-user-service:$GITHUB_SHA .
          docker build -t ghcr.io/${{ github.repository_owner }}/msa-user-service:latest .
          docker push ghcr.io/${{ github.repository_owner }}/msa-user-service:$GITHUB_SHA
          docker push ghcr.io/${{ github.repository_owner }}/msa-user-service:latest

      - name: send trigger
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/yunjeongwon/msa-infra/dispatches \
            -d '{"event_type":"deploy","client_payload":{"service":"user-service"}}'
            